name: betterserver
services:
  gameserver:
    build:
      context: https://github.com/saiv46/betterserver-oss.git#fork
      dockerfile: ./contrib/Dockerfile
    container_name: disaster2d-server
    init: false
    restart: unless-stopped
    mem_limit: 100M
    volumes:
      - ./data:/data
    ports:
      - 8606-8606:8606-8606/udp
